name: Deploy and update Lambda

on:
  pull_request:
    branches: 
      - main
    types: [closed]
    paths:
      - hello-world/**

env:
  AWS_REGION: us-east-1 
  ECR_REPOSITORY: hello-world   
  FUNCTION_NAME: hello-world
  IMAGE_URI: "903442739132.dkr.ecr.us-east-1.amazonaws.com/hello-world"

jobs:
  Deploy:
     if: github.event.pull_request.merged == true
     runs-on: ubuntu-latest
     name: Deploy
     environment: production
 
     steps:
       - name: Checkout
         uses: actions/checkout@v4
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.AWS_REGION }}
 
       - name: Login to Amazon ECR
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v2
 
       - name: Build, tag, and push image to Amazon ECR
         working-directory: hello-world
         id: build-image
         env:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
           IMAGE_TAG: ${{ github.sha }}
         run: |
           docker build -t hello-world .
           docker tag hello-world:$IMAGE_TAG $IMAGE_URI:$IMAGE_TAG
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
           echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

 
       - name: Update Lambda
         id: update-lambda
         run: |
           update-function-code --function-name $FUNCTION_NAME --image-uri $IMAGE_URI
 
       
 
 
 